### ISSUE TITLE
404

### ISSUE THREAD

**Issue by a-hauger** [ashnaguliani/JusticeForHarambe#3]
Hello!  I cannot access your Retro video; it gives me a 404.  Please comment tagging me when it has been fixed and I'll watch the video!  Thanks!

**Comment by ashnaguliani** [comment]
@a-hauger I changed the link and it should be fixed!

**Comment by cocr1742** [comment]
https://drive.google.com/open?id=0B5lkmhdxf_NZWXkxVXZXWU4zd3M oh sorry I
also just changed it lol

**Comment by a-hauger** [comment]
All set, thanks!
